export * from './academicCalendar/calendar.router';
export * from './dynamicPage/page.router';
export * from './employee/employee.router';
export * from './employeeCategory/employee.category.router';
export * from './gallery/gallery.router';
export * from './notice/notice.router';
export * from './sliders/slider.router';
export * from './systemSettings/system.router';
export * from './users/user.router';